#!/bin/bash
name=$(jq -r '.name' data.json)
height=$(jq -r '.height/10 | tostring + \"m\"' data.json)
weight=$(jq -r '.weight/10 | tostring + \"kg\"' data.json)
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
echo "${name^} is of type ${type^}, weighs $weight, and is $height tall."
